import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../app/theme/tokens.dart';
import '../../../core/errors/friendly_error.dart';
import '../../../core/widgets/fade_through_switcher.dart';
import '../../../core/widgets/loading_skeleton.dart';
import '../../../core/widgets/topic_chip.dart';
import '../../roadmap/models/roadmap_item.dart';
import '../controllers/lecture_insight_provider.dart';
import '../models/lecture_insight.dart';

/// Bottom sheet that shows the Gemini-generated digest of a lecture file.
/// Opened from a roadmap item's "Insights" action — works for both professor
/// (verify upload) and student (decide whether to study) flows.
class LectureInsightSheet extends ConsumerWidget {
  const LectureInsightSheet({required this.item, super.key});

  final RoadmapItem item;

  static Future<void> show(BuildContext context, RoadmapItem item) {
    return showModalBottomSheet<void>(
      context: context,
      useSafeArea: true,
      isScrollControlled: true,
      backgroundColor: Theme.of(context).colorScheme.surface,
      shape: const RoundedRectangleBorder(borderRadius: Radii.sheet),
      builder: (_) => LectureInsightSheet(item: item),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final request = LectureInsightRequest.fromRoadmapItem(item);
    final insight = ref.watch(lectureInsightProvider(request));
    final theme = Theme.of(context);
    final colors = theme.colorScheme;

    return Padding(
      padding: const EdgeInsets.fromLTRB(
        Spacing.xl,
        Spacing.lg,
        Spacing.xl,
        Spacing.xl,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: colors.outline,
                borderRadius: Radii.pill,
              ),
            ),
          ),
          const SizedBox(height: Spacing.lg),
          Row(
            children: [
              Container(
                width: 36,
                height: 36,
                decoration: BoxDecoration(
                  color: colors.primaryContainer,
                  borderRadius: Radii.button,
                ),
                child: Icon(
                  Icons.auto_awesome_outlined,
                  color: colors.onPrimaryContainer,
                  size: 18,
                ),
              ),
              const SizedBox(width: Spacing.md),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Lecture insights',
                      style: theme.textTheme.labelSmall,
                    ),
                    const SizedBox(height: 2),
                    Text(
                      item.title,
                      style: theme.textTheme.headlineSmall,
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: Spacing.lg),
          FadeThroughSwitcher(
            child: insight.when(
              loading: () => const KeyedSubtree(
                key: ValueKey('insight-loading'),
                child: _InsightSkeleton(),
              ),
              error: (err, _) => KeyedSubtree(
                key: const ValueKey('insight-error'),
                child: _InsightError(
                  message: friendlyErrorMessage(err),
                  onRetry: () =>
                      ref.invalidate(lectureInsightProvider(request)),
                ),
              ),
              data: (insight) => KeyedSubtree(
                key: const ValueKey('insight-data'),
                child: _InsightContent(insight: insight),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _InsightContent extends StatelessWidget {
  const _InsightContent({required this.insight});

  final LectureInsight insight;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.colorScheme;
    final sourceLabel = insight.source == LectureInsightSource.gemini
        ? 'Generated by Gemini'
        : 'Fallback view';

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(
              insight.source == LectureInsightSource.gemini
                  ? Icons.bolt_outlined
                  : Icons.info_outline,
              size: 14,
              color: colors.onSurfaceVariant,
            ),
            const SizedBox(width: 4),
            Text(
              sourceLabel,
              style: theme.textTheme.labelSmall?.copyWith(
                color: colors.onSurfaceVariant,
                letterSpacing: 0.4,
              ),
            ),
          ],
        ),
        const SizedBox(height: Spacing.sm),
        Text(
          'Summary',
          style: theme.textTheme.titleSmall,
        ),
        const SizedBox(height: Spacing.xs),
        Text(
          insight.summary,
          style: theme.textTheme.bodyLarge?.copyWith(height: 1.5),
        ),
        if (insight.topics.isNotEmpty) ...[
          const SizedBox(height: Spacing.lg),
          Text(
            'Key topics',
            style: theme.textTheme.titleSmall,
          ),
          const SizedBox(height: Spacing.sm),
          Wrap(
            spacing: Spacing.xs,
            runSpacing: Spacing.xs,
            children: [
              for (final topic in insight.topics) TopicChip(label: topic),
            ],
          ),
        ],
      ],
    );
  }
}

class _InsightSkeleton extends StatelessWidget {
  const _InsightSkeleton();

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const [
        LoadingSkeletonBar(width: 80, height: 12),
        SizedBox(height: Spacing.md),
        LoadingSkeletonBar(width: double.infinity, height: 14),
        SizedBox(height: Spacing.xs),
        LoadingSkeletonBar(width: double.infinity, height: 14),
        SizedBox(height: Spacing.xs),
        LoadingSkeletonBar(width: 240, height: 14),
        SizedBox(height: Spacing.lg),
        LoadingSkeletonBar(width: 100, height: 12),
        SizedBox(height: Spacing.sm),
        Wrap(
          spacing: Spacing.xs,
          runSpacing: Spacing.xs,
          children: [
            LoadingSkeletonBar(width: 80, height: 24, radius: 12),
            LoadingSkeletonBar(width: 110, height: 24, radius: 12),
            LoadingSkeletonBar(width: 90, height: 24, radius: 12),
          ],
        ),
      ],
    );
  }
}

class _InsightError extends StatelessWidget {
  const _InsightError({required this.message, required this.onRetry});

  final String message;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.colorScheme;
    return Container(
      padding: const EdgeInsets.all(Spacing.lg),
      decoration: BoxDecoration(
        color: colors.errorContainer,
        borderRadius: Radii.card,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Couldn\u2019t generate insights',
            style: theme.textTheme.titleSmall?.copyWith(color: colors.error),
          ),
          const SizedBox(height: 4),
          Text(
            message,
            style: theme.textTheme.bodyMedium?.copyWith(color: colors.error),
          ),
          const SizedBox(height: Spacing.md),
          Align(
            alignment: Alignment.centerRight,
            child: TextButton.icon(
              onPressed: onRetry,
              icon: const Icon(Icons.refresh, size: 16),
              label: const Text('Try again'),
            ),
          ),
        ],
      ),
    );
  }
}
