/// A digest of a lecture file: a short summary and the key topics covered.
/// Generated by Gemini from the file bytes on first open and cached in
/// memory for the session.
class LectureInsight {
  const LectureInsight({
    required this.summary,
    required this.topics,
    required this.source,
  });

  final String summary;
  final List<String> topics;
  final LectureInsightSource source;
}

enum LectureInsightSource {
  /// Extracted from the file by Gemini.
  gemini,

  /// Derived from file metadata + existing extracted topics, because no
  /// Gemini API key is configured.
  fallback,
}
